# Generated by Django 5.0 on 2023-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tegs',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
