# Generated by Django 5.0 on 2023-12-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('teg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tegs',
            field=models.ManyToManyField(blank=True, to='teg.tegs'),
        ),
    ]
