# Generated by Django 5.0 on 2023-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_tegs'),
        ('teg', '0002_alter_tegs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tegs',
            field=models.ManyToManyField(blank=True, related_name='Article_list', to='teg.tegs'),
        ),
    ]
